using System.Collections.Generic;

namespace XCoreNET.ClassModel
{
    class locateModel
    {
        public class translateModel
        {
            public string FONT_FAMILY { get; set; }
            public int FONT_SIZE { get; set; }
            public string FONT_FAMILY_CHILD { get; set; }
            public int FONT_SIZE_CHILD { get; set; }
            public string GROUP_MAIN_DATA { get; set; }
            public string GROUP_INSTANCE { get; set; }
            public string GROUP_ACCOUNT { get; set; }
            public string GROUP_LAUNCHER { get; set; }
            public string GROUP_VERSION_AND_INSTANCE_DATA { get; set; }
            public string GROUP_DOWNLOAD_MODE { get; set; }
            public string GROUP_MAX_MEMORY { get; set; }
            public string GROUP_STARTUP_PARMS { get; set; }
            public string GROUP_LAUNCHER_LANGUAGE { get; set; }
            public string GROUP_WEBVIEW2_DEFAULT { get; set; }
            public string GROUP_LAUNCHER_LOGIN_METHOD { get; set; }
            public string BTN_LAUNCH { get; set; }
            public string BTN_OPEN_FOLDER { get; set; }
            public string BTN_OPEN_VERIFY { get; set; }
            public string BTN_ADD_INSTANCE { get; set; }
            public string BTN_EDIT_INSTANCE { get; set; }
            public string BTN_REMOVE_INSTANCE { get; set; }
            public string BTN_ADD_ACCOUNT { get; set; }
            public string BTN_MULTI_ACCOUNT { get; set; }
            public string BTN_LOGOUT_ACCOUNT { get; set; }
            public string BTN_CHECK_UPDATE { get; set; }
            public string BTN_SETTINGS { get; set; }
            public string BTN_VER_INS_RELOAD { get; set; }
            public string BTN_VER_INS_RECACHE { get; set; }
            public string CHK_OPEN { get; set; }
            public string RAD_SINGLE { get; set; }
            public string RAD_CONCURRENCY { get; set; }
            public string TAB_MAIN { get; set; }
            public string TAB_SETTINGS { get; set; }
            public string TAB_OUTPUT_LOG { get; set; }
            public string TAB_CHANGELOG { get; set; }
            public string CONTENT_NONE { get; set; }
            public string CHK_DISABLED_WEBVIEW2 { get; set; }
            public string CHK_SETTING_MINECRAFT_TO_MAIN { get; set; }
            public string CHK_CHECKING_UPDATES_WHEN_START_UP { get; set; }
            public string LAB_CUSTOM_HOME_URL { get; set; }
            public string LAB_CUSTOM_LAUNCHER_URL { get; set; }
            public string LAB_CHANGE_LANGUAGE_NOTICE { get; set; }
            public string RAD_METHOD_DEFAULT { get; set; }
            public string RAD_METHOD_WEBVIEW2 { get; set; }
            public string RAD_METHOD_BROWSER { get; set; }
            public string BTN_OK { get; set; }
            public string BTN_APPLY { get; set; }
            public string BTN_INTRO { get; set; }
            public string BTN_RELOAD { get; set; }
            public string BTN_SWITCH { get; set; }
            public string BTN_DELETE { get; set; }
            public string FORM_TITLE_SETTINGS { get; set; }
            public string FORM_TITLE_MULTI_ACCOUNT { get; set; }
            public string FORM_TITLE_MICROSOFT_OAUTH { get; set; }
            public string FORM_TITLE_VERSION_SELECTOR { get; set; }
            public string FORM_TITLE_ADD_INSTANCE { get; set; }
            public string FORM_TITLE_EDIT_INSTANCE { get; set; }
            public string GROUP_INSTANCE_NAME { get; set; }
            public string GROUP_LAUNCH_BY_SPECIFIC_VERSION { get; set; }
            public string GROUP_CUSTOM_JAVA_PATH { get; set; }
            public string GROUP_CUSTOM_JVM { get; set; }
            public string LAB_INSTANCE_INTRO { get; set; }
            public string LAB_JAVA_PATH_INTRO { get; set; }
            public string GRID_VERSION { get; set; }
            public string GRID_TYPE { get; set; }
            public string GRID_DATE { get; set; }
            public string GRID_STATUS { get; set; }
            public string GRID_INSTALLED { get; set; }
            public string GRID_NON_INSTALLED { get; set; }
            public string GRID_DATE_FORMAT { get; set; }
            public string GROUP_STATUS_FILTER { get; set; }
            public string GROUP_VERSION_FILTER { get; set; }
            public string RAD_STATUS_ALL { get; set; }
            public string RAD_STATUS_INSTALL { get; set; }
            public string RAD_STATUS_NON_INSTALL { get; set; }
            public string CHK_VERSION_RELEASE { get; set; }
            public string CHK_VERSION_SNAPSHOT { get; set; }
            public string CHK_VERSION_LOADER { get; set; }
            public string CHK_SAVE_LOG { get; set; }
            public string LAB_LOADING { get; set; }
            public string LAB_CHANGELOG_DATE_FORMAT { get; set; }
            public string LAB_CHANGELOG_RSS_ERROR { get; set; }
            public string DIALOG_WARNING { get; set; }
            public string DIALOG_ERROR { get; set; }
            public string DIALOG_INFO { get; set; }
            public string DIALOG_REPLACE_DEFAULT_PATH { get; set; }
            public string DIALOG_LOGOUT { get; set; }
            public string DIALOG_CHOOSE_NEW_MINECRAFT_PATH { get; set; }
            public string DIALOG_CANT_DELETE_INSTANCE { get; set; }
            public string DIALOG_DELETE_INSTANCE_CONFIRM { get; set; }
            public string DIALOG_CANT_FIND_INSTANCE { get; set; }
            public string DIALOG_NO_XBOX_ACCOUNT { get; set; }
            public string DIALOG_XBOX_NOT_AVAILABLE { get; set; }
            public string DIALOG_XBOX_IS_CHILD { get; set; }
            public string DIALOG_NO_MINECRAFT_ACCOUNT { get; set; }
            public string DIALOG_CANT_EDIT_INSTANCE { get; set; }
            public string DIALOG_INSTANCE_INTRO { get; set; }
            public string DIALOG_INSTANCE_EXIST { get; set; }
            public string DIALOG_CREATE_UNEXPECTED { get; set; }
            public string DIALOG_INSTANCE_NO_NAME { get; set; }
            public string DIALOG_JAVA_PATH_INTRO { get; set; }
            public string DIALOG_NO_JAVA_EXIST { get; set; }
            public string DIALOG_DELETE_ACCOUNT_CONFIRM { get; set; }
            public string TOOLTIP_REFRESH_ACCESS_TOKEN { get; set; }
            public string TOOLTIP_SWITCH_ACCOUNT { get; set; }
            public string TOOLTIP_DELETE_ACCOUNT { get; set; }
            public string DIALOG_PARMS_RESTART_CONFIRM { get; set; }
            public string DIALOG_LANG_RESTART_CONFIRM { get; set; }
            public string TOOLTIP_GRID_DATE_INTRO { get; set; }
            public string TOOLTIP_OPEN_FOLDER { get; set; }
            public string TOOLTIP_VERIFY_FILE { get; set; }
            public string TOOLTIP_RELOAD { get; set; }
            public string TOOLTIP_RECACHE { get; set; }
            public string TOOLTIP_DOWNLOAD_SINGLE { get; set; }
            public string TOOLTIP_DOWNLOAD_CONCURRENCY { get; set; }
            public string DIALOG_APPLICATION_LATEST { get; set; }
            public string DIALOG_APPLICATION_CHECKING_UPDATE_ERROR { get; set; }
            public string DIALOG_APPLICATION_UPDATE_CONFIRM { get; set; }
            public string LAB_SLOGAN { get; set; }
            public string BTN_LOGIN_MICROSOFT { get; set; }
            public string BTN_SWITCH_ACCOUNT { get; set; }
            public string FORM_TITLE_SWITCHING_ACCOUNT { get; set; }
            public string DIALOG_NO_VALID_VERSION { get; set; }
            public string LOGGER_NO_CLIENT_PROFILE { get; set; }
            public string DIALOG_NO_VANILLA_VERSION { get; set; }
            public string DIALOG_INSTALL_VANILLA_CONFIRM { get; set; }
            public string LOGGER_CREATE_INDEXES { get; set; }
            public string LOGGER_CREATE_GAME_APPLICATION { get; set; }
            public string LOGGER_GAME_APPLICATION_VERIFY_FAILD { get; set; }
            public string LOGGER_DOWNLOAD_GAME_APPLICATION { get; set; }
            public string LOGGER_GAME_APPLICATION_COMPLETE { get; set; }
            public string LOGGER_CREATE_LOGGER_CONFIGURATION { get; set; }
            public string LOGGER_CREATE_JAVA_RUNTIME { get; set; }
            public string LOGGER_INDEXING_JAVA_RUNTIME { get; set; }
            public string LOGGER_DOWNLOADING_JAVA_RUNTIME { get; set; }
            public string LOGGER_CHECKING_JAVA_RUNTIME { get; set; }
            public string LOGGER_PREPARE_PARALLEL_DOWNLOAD_JAVA_RUNTIME { get; set; }
            public string LOGGER_PREPARE_PARALLEL_DOWNLOAD_NECESSARY_FILE { get; set; }
            public string LOGGER_PREPARE_PARALLEL_DOWNLOAD_ASSETS { get; set; }
            public string LOGGER_CREATE_NECESSARY_FILE { get; set; }
            public string LOGGER_CATCH_NECESSARY_FILE_INDEXES { get; set; }
            public string LOGGER_CATCH_NECESSARY_FILE_INDEXES_CUSTOM { get; set; }
            public string LOGGER_CHECKING_NECESSARY_FILE { get; set; }
            public string LOGGER_INDEXING_NECESSARY_FILE { get; set; }
            public string LOGGER_DOWNLOAD_NECESSARY_FILE { get; set; }
            public string LOGGER_NECESSARY_FILE_COMPLETE { get; set; }
            public string LOGGER_VERIFY_FILE_FAILED { get; set; }
            public string LOGGER_CREATE_ASSETS { get; set; }
            public string LOGGER_INDEXING_ASSETS { get; set; }
            public string LOGGER_DOWNLOAD_ASSETS { get; set; }
            public string LOGGER_CHECKING_ASSETS { get; set; }
            public string LOGGER_CHECKING_COMPLETE { get; set; }
            public string LOGGER_UNZIPPING_NECESSARY_FILE { get; set; }
            public string DIALOG_UNZIPPING_ERROR { get; set; }
            public string LOGGER_COMPATIBILITY_OLDER_VERSION { get; set; }
            public string LOGGER_LAUNCHING_GAME { get; set; }
            public string DIALOG_KILL_CHILD_PROCESS_CONFIRM { get; set; }
            public string LOGGER_GAME_CLOSED { get; set; }
            public string LOGGER_GAME_FORCING_CLOSED { get; set; }
            public string DIALOG_CLOSING_LAUNCHER_CONFIRM { get; set; }
            public string DIALOG_JVM_ERROR { get; set; }
            public string LOGGER_VERIFYING_AZURE { get; set; }
            public string LOGGER_VERIFYING_AZURE_COMPLETE { get; set; }
            public string LOGGER_GETTING_REFRESH_TOKEN { get; set; }
            public string LOGGER_GETTING_REFRESH_TOKEN_COMPLETE { get; set; }
            public string LOGGER_GETTING_XBL_TOKEN { get; set; }
            public string LOGGER_GETTING_XBL_TOKEN_COMPLETE { get; set; }
            public string LOGGER_GETTING_XSTS_TOKEN { get; set; }
            public string LOGGER_GETTING_XSTS_TOKEN_COMPLETE { get; set; }
            public string LOGGER_GETTING_MINECRAFT_TOKEN { get; set; }
            public string LOGGER_GETTING_MINECRAFT_TOKEN_COMPLETE { get; set; }
            public string LOGGER_CHECKING_MINECRAFT_OWNERSHIP { get; set; }
            public string LOGGER_CHECKING_MINECRAFT_OWNERSHIP_COMPLETE { get; set; }
            public string LOGGER_GETTING_MINECRAFT_PROFILE { get; set; }
            public string LOGGER_GETTING_MINECRAFT_PROFILE_COMPLETE { get; set; }
            public string LOGGER_LOGIN_USER { get; set; }
            public string LOGGER_PARALLEL_DOWNLOADING { get; set; }
            public string LOGGER_PARALLEL_DOWNLOADING_TYPE_JAVA_RUNTIME { get; set; }
            public string LOGGER_PARALLEL_DOWNLOADING_TYPE_NECESSARY_FILE { get; set; }
            public string LOGGER_PARALLEL_DOWNLOADING_TYPE_ASSETS { get; set; }
            public string LOGGER_PARALLEL_DOWNLOADING_TYPE_APPLICATION { get; set; }
            public string LOGGER_DOWNLOAD_COMPLETE { get; set; }
            public string LOGGER_DOWNLOAD_CANCELED { get; set; }
            public string LOGGER_DOWNLOAD_FAILED { get; set; }
            public string FORM_TITLE_UPDATER { get; set; }
            public string BTN_CANCEL { get; set; }
            public string LAB_UPDATING { get; set; }
            public string LAB_INITIALIZING { get; set; }
            public string LAB_INITIALIZING_DOWNLOAD { get; set; }
            public string LAB_PREPARING_DOWNLOAD { get; set; }
            public string LAB_APPLICATION_LATEST { get; set; }
            public string LAB_ERROR { get; set; }
            public string LAB_DOWNLOADING { get; set; }
            public string LAB_DOWNLOADED { get; set; }
            public string LAB_PREPARING_INSTALL { get; set; }
            public string DIALOG_CANT_LOGIN_MICROSOFT { get; set; }
            public string DIALOG_REDIRECT_WEBVIEW2_CONFIRM { get; set; }
            public string DIALOG_NO_WEBVIEW2 { get; set; }
            public string DIALOG_BROWSER_CONFIRM { get; set; }
            public string DIALOG_LOGIN_FAILED { get; set; }
            public string DIALOG_TRAY_MAIN { get; set; }
            public string TRAY_CLOSE_GAME { get; set; }
            public string TRAY_CLOSE_LAUNCHER { get; set; }
            public string HTML_OAUTH_COMPLETE { get; set; }
        }
        public class manifestListModel
        {
            public List<manifestModel> locates { get; set; }
        }
        public class manifestModel
        {
            public string name { get; set; }
            public string displayName { get; set; }
            public string country { get; set; }
        }
    }
}
