//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCoreNET.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XCoreNET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似                        GNU通用公共授權
        ///                    第三版 2007年6月29日
        ///
        ///版權所有（C）2007 Free Software Foundation, Inc. (http://fsf.org)
        ///
        ///允許所有人複製和發佈本授權文件的完整版本，但不允許對它進行任何修改。
        ///
        ///
        ///導言
        ///GNU通用公共授權是一份針對軟體和其他種類作品的自由的、公共的授權文件。
        ///
        ///大多數軟體授權申明被設計爲剝奪您共用和修改軟體的自由。相反地，GNU通用公共授權力圖保護您分享和修改自由軟體地自由——以確保軟體對所有使用者都是自由的。我們，自由軟體基金會，對我們的大多數軟體使用GNU通用公共授權；本授權同樣適用于任何其作者以這種方式發佈的軟體。您也可以讓您的軟體使用本授權。
        ///
        ///當我們談論自由軟體時，我們指的是行爲的自由，而非價格免費。GNU通用公共授權被設計爲確保您擁有發佈自由軟體副本(以及爲此收費，如果您希望的話)的自由,確保您能收到原始碼或者在您需要時能獲取原始碼，確保您能修改軟體或者將它的一部分用於新的自由軟體，並且確保您知道您能做這些事情。
        ///
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 MIT License
        ///
        ///Copyright (c) 2009 - 2010 Microsoft Coropration, then modifications by Peter William Wagner 2017 - 2021
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to d [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string WindowsAPICodePack {
            get {
                return ResourceManager.GetString("WindowsAPICodePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] XCoreNET_Updater {
            get {
                object obj = ResourceManager.GetObject("XCoreNET_Updater", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;startup&gt; 
        ///        &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.7.2&quot; /&gt;
        ///    &lt;/startup&gt;
        ///&lt;/configuration&gt; 的當地語系化字串。
        /// </summary>
        internal static string XCoreNET_Updater_exe {
            get {
                return ResourceManager.GetString("XCoreNET_Updater_exe", resourceCulture);
            }
        }
    }
}
